### ISSUE TITLE
Support for configurable causation metadata key

### ISSUE THREAD

**Issue by pkruithof** [prooph/event-store-bus-bridge#39]
The causation enricher adds the metadata with the key `_causation_id`:

https://github.com/prooph/event-store-bus-bridge/blob/bc2067ef9eb0e2ff3079854dc3330f8412d2d318/src/CausationMetadataEnricher.php#L132

When using eventstore.org (for example), this needs to be `$causationId`. We could make this configurable, by injecting the names in the constructor. Alternatively we could introduce something like a `Generator` with a default and eventstore.org implementation.

**Comment by prolic** [comment]
Injecting via constructor sounds good, but let's leave the current value of `_causation_id` by default for BC reasons. Wanna give it a shot?
